### PR TITLE
Add --track-generated-files to parol new

### LINKED ISSUE #32: [parol new] Generate .gitignore to ignore generated files (opt-in or opt-out)
I think that in most use-case:
1. users want to put generated files in `src` for easy reference and better IDE support.
2. users don't want to maintain the generated files under git control not to include derived differences in the history.

1 has already been achieved.
About 2, some users may be surprised that git is going to track the generated files.

I believe an opt-out behavior like `parol new --track-generated-files` would be preferred.

After hearing other opinions, I'll create a pull-req for this.

### PR DESCRIPTION
**Pull request by ryo33**
Closes #32

### CODE REVIEW

**Comment by ryo33** [comment]
I need one more commit.

**Comment by ryo33** [comment]
Now it works.

**Review by jsinger67 — APPROVED** [review]
👍

**Review by jsinger67 — APPROVED** [review]
Fine 👍

**Pull request merged**
