### PR TITLE
Update PAR grammar link in the book

### PR DESCRIPTION
**Pull request by ryo33**
I forgot to update it.

### CODE REVIEW

**Review by jsinger67 — APPROVED** [review]
Yes, I also missed this. Thanks for this PR.
As you might have noticed I completely removed the EBNF version of parol's grammar because it must always be separately updated when changes are made and - as you noted - it can be rather disrupting for the reader.

**Comment by jsinger67** [comment]
I will update the live book soon.

**Comment by ryo33** [comment]
> As you might have noticed I completely removed the EBNF version of parol's grammar because it must always be separately updated when changes are made and - as you noted - it can be rather disrupting for the reader.

Yeah, I've noticed, and I think it's good.

**Comment by ryo33** [comment]
It is really great that the grammar of PAR seems to be readable by anyone who knows BNF.

**Pull request merged**
