### PR TITLE
Cargo Workspace

### LINKED ISSUE #21: How about cargo workspace
Currently, each parol-related crate seems to have its own GitHub repository. We can use [cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) to make them into one repository.
As a user, I think the workspace style is easier to refer to the code. Best of all, it eliminates the need for multiple git clones.
Also, monorepo would be more advantageous in terms of maintenance.

Many of the libraries I'm following seem to use the workspace style:
- [Bevy](https://github.com/bevyengine/bevy)
- [Rapier](https://github.com/dimforge/rapier)

### PR DESCRIPTION
**Pull request by ryo33**
Closes #21

### CODE REVIEW

**Comment by ryo33** [comment]
We need one more commit. I'll push it soon.

**Comment by ryo33** [comment]
> We need one more commit. I'll push it soon.

Done!

**Comment by ryo33** [comment]
I've opened https://github.com/maghoff/bart/pull/25.

**Comment by ryo33** [comment]
Suggested refinements after the merge:
- [ ] use path dependencies in examples/basic_interpreter/Cargo.toml and examples/json_parser/Cargo.toml
- [ ] correct inconsistencies in crate names such as parol-macros and parol_runtime.
- [ ] Use the latest `bart` if this merged: https://github.com/maghoff/bart/pull/25

**Review by jsinger67 — APPROVED** [review]
Way too much to review 😉
Just merging👍
Thanks a lot @ryo33, huge benefit!

**Comment by jsinger67** [comment]
https://github.com/maghoff/bart/pull/25 is untouched.
Seems to be very low activity at this project, which is sad.
I hope, we get your PR through in a reasonable period of time.

**Comment by ryo33** [comment]
The author has put ❤️  reaction to it!

**Comment by jsinger67** [comment]
Yeah, that's reassuring 👍

**Comment by jsinger67** [comment]
@ryo33 I see no progress at `bart`.
I consider to temporarily remove `bart` form `parol_runtime`'s rexport and explicitly reference it as long as your PR is not included.
This is only to workaround that I can't release crates on crates.io which have no valid version (this holds for your clone of `bart` that I'm referencing now).
What do you think?

**Comment by ryo33** [comment]
https://github.com/jsinger67/parol/issues/46
I’d like to try to replace bart in this issue.

**Comment by jsinger67** [comment]
Ok, if there are comparable crates available this would be a reasonable decision 👍

**Comment by ryo33** [comment]
I tried several workarounds to use the released version of bart, but they were all difficult, and I regret that I may have made a mistake in choosing the cargo workspace. At the moment, I am working on replacing bart.

**Comment by jsinger67** [comment]
Overall I don't think that it was a mistake to switch to a Workspace layout.
If we can't find a suitable replacement for bart, we can temporarily add the reference to it explicitly thereby opting out of the use of re-exporting it from parol_runtime (and commenting out the library specification in the template).
Such a situation can always happen, regardless of using a Workspace or not.
So, no regrets necessary 😉

**Comment by maghoff** [comment]
Sorry for being so late in following up bart. Such is life! For what it's worth, I have now finally been able to publish a release with the patch included :slightly_smiling_face: Good luck going forward, regardless of your choice of templating engine :wink:

**Comment by jsinger67** [comment]
Thank you very much @maghoff.
We all do this mostly in our spare time and just for fun. I appreciate your work a lot, anyway.
Good luck for you too 😊

**Pull request merged**
